---
- name: Install RPMFusion Free RPM
  dnf:
    name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_major_version}}.noarch.rpm"
    state: present
- name: Install RPMFusion Non-Free RPM
  dnf:
    name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-nonfree-release-{{ansible_major_version}}.noarch.rpm"
    state: present
  when: nonfree is True
